"""empty message

Revision ID: 238ae95ed3ba
Revises: 
Create Date: 2020-04-20 12:34:07.272630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238ae95ed3ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('series', sa.String(length=3), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=False),
    sa.Column('isin_number', sa.String(length=20), nullable=False),
    sa.Column('face_value', sa.Integer(), nullable=False),
    sa.Column('company_detail', sa.Text(), nullable=True),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('exchange_name', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('stock_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('prev_price', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('traded_qty', sa.Integer(), nullable=True),
    sa.Column('delivery_qty', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=3), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('trade_timeframe', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_no', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_stock')
    op.drop_table('stock_report')
    op.drop_table('user')
    op.drop_table('stock')
    # ### end Alembic commands ###
