"""empty message

Revision ID: 6b7fb764a001
Revises: 
Create Date: 2020-04-09 02:16:45.648205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7fb764a001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_day_report', sa.Column('series', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_day_report', 'series')
    # ### end Alembic commands ###
