"""empty message

Revision ID: 84d6f86780c4
Revises: bf6947a9714b
Create Date: 2020-05-11 15:54:30.657326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d6f86780c4'
down_revision = 'bf6947a9714b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stock', sa.Column('public_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'stock', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_column('stock', 'public_id')
    op.drop_table('fund')
    # ### end Alembic commands ###
