"""empty message

Revision ID: e6223fcdd59a
Revises: 7f585a4bae59
Create Date: 2020-04-28 22:44:37.994129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6223fcdd59a'
down_revision = '7f585a4bae59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('executed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'executed_date')
    # ### end Alembic commands ###
