"""empty message

Revision ID: f9389848ce82
Revises: fe365ddfad56
Create Date: 2020-04-08 11:31:19.212261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9389848ce82'
down_revision = 'fe365ddfad56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_day_report', sa.Column('last_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_day_report', 'last_price')
    # ### end Alembic commands ###
